#!/usr/bin/env ruby

require 'c2h'
require 'choice'

Choice.options do

  option :configfile do
    short '-c'
    long '--conf pad/to/configfile'
    desc 'Location of your configfile'
    desc '(default contentful.yml)'
    default 'contentful.yml'
  end

  option :help do
    long '--help'
    desc 'Show this message'
  end

  option :verbose do
    long '--verbose'
    short '-v'
    desc 'Give more output'
  end

  option :version do
    long '--version'
    desc 'Show version'
    action do
      puts "c2h Contentful 2 Hugo v#{C2H::VERSION}"
      exit 0
    end
  end

  option :debug do
    long '--debug'
    short '-d'
    desc 'Full debug logging'
  end
end

begin
  mapper = C2H::Mapper.new(Choice.choices)
  mapper.run
rescue => e
  puts "#{e.class}: #{e.message}\n\n\t#{e.backtrace.join("\n\t")}\n"
  exit 1
end

exit 0
